import { useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { useAuth } from '../auth';
import { get, patch, post, put } from '../lib/api';
import { dateTime } from '../lib/format';
import { useT } from '../lib/i18n';
import { Alert, AuditTimeline, Dialog, EmptyState, ErrorState, ForbiddenState, Loading, NumField, SelectField, StatusBadge, Tabs, TextField, AreaField } from '../components/ui';
import { PageHead, roleLabel } from '../components/Shell';

export function UsersPage() {
  const t = useT(); const { can } = useAuth(); const qc = useQueryClient();
  const [inv, setInv] = useState(false); const [edit, setEdit] = useState<any>(null); const [link, setLink] = useState('');
  const u = useQuery({ queryKey: ['users'], queryFn: () => get<any>('/users'), enabled: can('user.manage') });
  const plants = useQuery({ queryKey: ['plants'], queryFn: () => get<any[]>('/plants') });
  if (!can('user.manage')) return <div className="page"><ForbiddenState /></div>;
  if (u.isLoading) return <div className="page"><Loading /></div>;
  if (u.error) return <div className="page"><ErrorState error={u.error} /></div>;
  const reload = () => void qc.invalidateQueries({ queryKey: ['users'] });
  return (
    <div className="page">
      <PageHead title={t('Users')}><button className="btn-primary" onClick={() => setInv(true)}>{t('Invite user')}</button></PageHead>
      <div className="table-wrap"><table className="t"><thead><tr><th>{t('Name')}</th><th>{t('Email')}</th><th>{t('Role')}</th><th>{t('Plants')}</th><th>{t('Status')}</th><th /></tr></thead><tbody>
        {u.data.users.map((x: any) => <tr key={x.membershipId}><td>{x.name}</td><td className="ltr">{x.email}</td><td>{t(roleLabel(x.role))}{(x.grant.length > 0 || x.revoke.length > 0) && <span className="chip" style={{ marginInlineStart: 6 }}>{t('custom')}</span>}</td>
          <td>{x.allPlants || x.role === 'admin' ? t('All plants') : x.plantIds.map((p: string) => plants.data?.find((y) => y.id === p)?.code).join(', ') || <span className="badge warn">{t('None assigned')}</span>}</td><td><StatusBadge status={x.status} /></td><td className="hstack"><button className="btn-sm" onClick={() => setEdit(x)}>{t('Edit')}</button><button className="btn-sm" onClick={async () => { await post(`/users/${x.membershipId}/revoke-sessions`); reload(); }}>{t('Sign out everywhere')}</button></td></tr>)}</tbody></table></div>
      {u.data.invitations.length > 0 && <div className="card" style={{ marginTop: 16 }}><h2>{t('Pending invitations')}</h2>{u.data.invitations.map((i: any) => <div key={i.id} className="qitem"><span className="ltr">{i.email}</span><span className="muted small">{t(roleLabel(i.role))} · {t('expires')} {dateTime(i.expiresAt)}</span></div>)}</div>}
      {inv && <InviteDialog plants={plants.data ?? []} onClose={() => setInv(false)} onDone={(l: string) => { setInv(false); setLink(l); reload(); }} />}
      {link && <Dialog title={t('Invitation link')} onClose={() => setLink('')}><Alert tone="warn">{t('Copy this one-time link now and send it through a trusted channel. It is shown once, expires, and works only once. Nothing is emailed automatically.')}</Alert><p className="ltr" style={{ wordBreak: 'break-all', userSelect: 'all' }} data-testid="invite-link">{link}</p></Dialog>}
      {edit && <EditUser x={edit} caps={u.data.capabilities} plants={plants.data ?? []} onClose={() => setEdit(null)} onDone={() => { setEdit(null); reload(); }} />}
    </div>
  );
}
function InviteDialog({ plants, onClose, onDone }: any) {
  const t = useT(); const [f, setF] = useState({ email: '', role: 'sales', plantIds: [] as string[], allPlants: false }); const [err, setErr] = useState('');
  const go = async () => { try { const r = await post('/users/invitations', f); onDone(r.link); } catch (e) { setErr((e as Error).message); } };
  return <Dialog title={t('Invite user')} onClose={onClose} footer={<><button onClick={onClose}>{t('Cancel')}</button><button className="btn-primary" disabled={!f.email} onClick={go}>{t('Create invitation link')}</button></>}>
    <div className="stack">{err && <Alert tone="err">{err}</Alert>}<TextField label={t('Email')} type="email" dir="ltr" value={f.email} onChange={(e) => setF({ ...f, email: e.target.value })} />
      <SelectField label={t('Role')} value={f.role} onChange={(e) => setF({ ...f, role: e.target.value })}>{['admin', 'pricing', 'technical', 'sales', 'viewer'].map((r) => <option key={r} value={r}>{t(roleLabel(r))}</option>)}</SelectField>
      <label className="hstack"><input type="checkbox" checked={f.allPlants} onChange={(e) => setF({ ...f, allPlants: e.target.checked })} />{t('Access to all plants')}</label>
      {!f.allPlants && <fieldset style={{ border: 0, padding: 0 }}><legend style={{ fontWeight: 550, fontSize: 14 }}>{t('Plants')}</legend>{plants.map((p: any) => <label key={p.id} className="hstack" style={{ minHeight: 36 }}><input type="checkbox" checked={f.plantIds.includes(p.id)} onChange={(e) => setF({ ...f, plantIds: e.target.checked ? [...f.plantIds, p.id] : f.plantIds.filter((x) => x !== p.id) })} />{p.nameEn}</label>)}</fieldset>}</div></Dialog>;
}
function EditUser({ x, caps, plants, onClose, onDone }: any) {
  const t = useT(); const [role, setRole] = useState(x.role); const [grant, setGrant] = useState<string[]>(x.grant); const [revoke, setRevoke] = useState<string[]>(x.revoke); const [all, setAll] = useState(x.allPlants); const [pids, setPids] = useState<string[]>(x.plantIds); const [status, setStatus] = useState(x.status); const [err, setErr] = useState('');
  const toggle = (c: string, set: string[], fn: (v: string[]) => void) => fn(set.includes(c) ? set.filter((y) => y !== c) : [...set, c]);
  const go = async () => { try { await patch(`/users/${x.membershipId}`, { role, grant, revoke, allPlants: all, plantIds: pids, status }); onDone(); } catch (e) { setErr((e as Error).message); } };
  return <Dialog wide title={t('Edit {n}', { n: x.name })} onClose={onClose} footer={<><button onClick={onClose}>{t('Cancel')}</button><button className="btn-primary" onClick={go}>{t('Save changes')}</button></>}>
    <div className="stack">{err && <Alert tone="err">{err}</Alert>}<div className="row"><SelectField label={t('Role')} value={role} onChange={(e) => setRole(e.target.value)}>{['admin', 'pricing', 'technical', 'sales', 'viewer'].map((r) => <option key={r} value={r}>{t(roleLabel(r))}</option>)}</SelectField>
      <SelectField label={t('Status')} value={status} onChange={(e) => setStatus(e.target.value)}><option value="active">{t('Active')}</option><option value="disabled">{t('Disabled')}</option></SelectField></div>
      <label className="hstack"><input type="checkbox" checked={all} onChange={(e) => setAll(e.target.checked)} />{t('Access to all plants')}</label>
      {!all && <div className="hstack">{plants.map((p: any) => <label key={p.id} className="hstack"><input type="checkbox" checked={pids.includes(p.id)} onChange={() => toggle(p.id, pids, setPids)} />{p.nameEn}</label>)}</div>}
      <details className="adv"><summary>{t('Capability overrides on top of the role preset')}</summary><div className="grid2" style={{ marginTop: 8 }}>{caps.map((c: string) => <div key={c} className="small"><span className="ltr">{c}</span><div className="hstack"><label className="hstack"><input type="checkbox" checked={grant.includes(c)} onChange={() => toggle(c, grant, setGrant)} />{t('Grant')}</label><label className="hstack"><input type="checkbox" checked={revoke.includes(c)} onChange={() => toggle(c, revoke, setRevoke)} />{t('Revoke')}</label></div></div>)}</div></details></div></Dialog>;
}

export function AuditPage() {
  const t = useT(); const { can } = useAuth(); const [type, setType] = useState('');
  const a = useQuery({ queryKey: ['audit', type], queryFn: () => get<any[]>(`/audit?limit=200${type ? `&entityType=${type}` : ''}`), enabled: can('audit.view') });
  if (!can('audit.view')) return <div className="page"><ForbiddenState /></div>;
  return (
    <div className="page"><PageHead title={t('Audit History')} sub={t('Append-only record of changes. It cannot be edited or deleted.')} />
      <div className="toolbar"><SelectField label={t('Entity')} value={type} onChange={(e) => setType(e.target.value)}><option value="">{t('All')}</option>{['quotation', 'price_batch', 'material_price', 'plant_cost', 'forecast', 'mix', 'tax_policy', 'terms', 'pricing_policy', 'membership', 'invitation', 'tenant', 'client', 'project', 'plant', 'material', 'user'].map((x) => <option key={x} value={x}>{x}</option>)}</SelectField></div>
      {a.isLoading && <Loading />}{a.error && <ErrorState error={a.error} />}
      {a.data && !a.data.length && <EmptyState title={t('No events')} />}
      {a.data && a.data.length > 0 && <div className="table-wrap"><table className="t"><thead><tr><th>{t('When (UTC)')}</th><th>{t('Who')}</th><th>{t('Entity')}</th><th>{t('Action')}</th><th>{t('Detail')}</th></tr></thead><tbody>
        {a.data.map((e) => <tr key={e.id}><td className="ltr">{dateTime(e.at)}</td><td>{e.actorLabel ?? t('System')}</td><td>{e.entityType} <span className="muted small ltr">{String(e.entityId).slice(0, 8)}</span></td><td>{e.action.replaceAll('_', ' ')}</td><td className="small muted" style={{ maxWidth: 360, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }} title={JSON.stringify(e.detail)}>{e.detail?.comment ?? JSON.stringify(e.detail).slice(0, 120)}</td></tr>)}</tbody></table></div>}</div>
  );
}

export function SettingsPage() {
  const t = useT(); const { can } = useAuth(); const [tab, setTab] = useState('company');
  const tabs = [{ id: 'company', label: t('Company'), c: ['tenant.manage'] }, { id: 'plants', label: t('Plants'), c: ['tenant.manage'] }, { id: 'materials', label: t('Materials'), c: ['material.manage'] }, { id: 'tax', label: t('Tax policies'), c: ['tax.manage', 'tax.verify'] }, { id: 'terms', label: t('Terms'), c: ['terms.manage'] }, { id: 'policies', label: t('Pricing policies'), c: ['policy.manage'] }].filter((x) => can(...x.c));
  if (!tabs.length) return <div className="page"><ForbiddenState /></div>;
  const cur = tabs.find((x) => x.id === tab) ?? tabs[0]!;
  return <div className="page"><PageHead title={t('Company Settings')} /><Tabs tabs={tabs} value={cur.id} onChange={setTab} />
    {cur.id === 'company' && <CompanyTab />}{cur.id === 'plants' && <PlantsTab />}{cur.id === 'materials' && <MaterialsTab />}{cur.id === 'tax' && <TaxTab />}{cur.id === 'terms' && <TermsTab />}{cur.id === 'policies' && <PoliciesTab />}</div>;
}
function CompanyTab() {
  const t = useT(); const s = useQuery({ queryKey: ['settings'], queryFn: () => get<any>('/settings') }); const [f, setF] = useState<any>(null); const [ok, setOk] = useState(false); const [err, setErr] = useState('');
  if (s.isLoading) return <Loading />; if (!f && s.data) setTimeout(() => setF(s.data.settings), 0); if (!f) return <Loading />;
  const set = (k: string, v: any) => setF({ ...f, [k]: v }); const co = (k: string, v: string) => setF({ ...f, company: { ...f.company, [k]: v } });
  const save = async () => { setErr(''); setOk(false); try { await put('/settings', { separateProposerApprover: f.separateProposerApprover, separateQuoteSubmitterApprover: f.separateQuoteSubmitterApprover, staleAfterDays: f.staleAfterDays, defaultValidityDays: f.defaultValidityDays, internalDp: f.internalDp, company: f.company }); setOk(true); } catch (e) { setErr((e as Error).message); } };
  return <div className="card stack">{err && <Alert tone="err">{err}</Alert>}{ok && <Alert tone="ok">{t('Settings saved.')}</Alert>}
    <h2>{t('Company details (printed on quotations)')}</h2><div className="grid2"><TextField label={t('Company name')} value={f.company.name} onChange={(e) => co('name', e.target.value)} /><TextField label={t('Short name for the logo area')} value={f.company.logoText} onChange={(e) => co('logoText', e.target.value)} /><TextField label={t('Address')} value={f.company.address} onChange={(e) => co('address', e.target.value)} /><TextField label={t('Phone')} dir="ltr" value={f.company.phone} onChange={(e) => co('phone', e.target.value)} /><TextField label={t('Email')} dir="ltr" value={f.company.email} onChange={(e) => co('email', e.target.value)} /><TextField label={t('Tax number')} dir="ltr" value={f.company.taxNumber} onChange={(e) => co('taxNumber', e.target.value)} /></div>
    <h2>{t('Controls')}</h2><div className="grid2"><NumField label={t('Price freshness threshold')} unit={t('days')} value={String(f.staleAfterDays)} onChange={(v) => set('staleAfterDays', Number(v) || 1)} /><NumField label={t('Default quotation validity')} unit={t('days')} value={String(f.defaultValidityDays)} onChange={(v) => set('defaultValidityDays', Number(v) || 1)} /><NumField label={t('Internal unit-rate precision')} unit={t('decimals')} value={String(f.internalDp)} onChange={(v) => set('internalDp', Math.min(6, Math.max(3, Number(v) || 4)))} hint={t('Customer amounts are always rounded to 3 decimals (JOD).')} /></div>
    <label className="hstack"><input type="checkbox" checked={f.separateProposerApprover} onChange={(e) => set('separateProposerApprover', e.target.checked)} />{t('Require a different user to approve price batches, cost versions and mix revisions')}</label>
    <label className="hstack"><input type="checkbox" checked={f.separateQuoteSubmitterApprover} onChange={(e) => set('separateQuoteSubmitterApprover', e.target.checked)} />{t('Require a different user to approve a submitted quotation')}</label>
    <button className="btn-primary" style={{ alignSelf: 'flex-start' }} onClick={save}>{t('Save settings')}</button></div>;
}
function PlantsTab() {
  const t = useT(); const qc = useQueryClient(); const p = useQuery({ queryKey: ['plants'], queryFn: () => get<any[]>('/plants') }); const [d, setD] = useState<any>(null); const [err, setErr] = useState('');
  const save = async () => { try { d.id ? await put(`/plants/${d.id}`, d) : await post('/plants', d); setD(null); void qc.invalidateQueries({ queryKey: ['plants'] }); } catch (e) { setErr((e as Error).message); } };
  return <div className="card"><div className="card-head"><h2>{t('Plants')}</h2><span className="grow" /><button className="btn-primary" onClick={() => setD({ code: '', nameEn: '', nameAr: '', address: '' })}>{t('Add plant')}</button></div>
    <div className="table-wrap"><table className="t"><thead><tr><th>{t('Code')}</th><th>{t('Name')}</th><th>{t('Name (Arabic)')}</th><th /></tr></thead><tbody>{(p.data ?? []).map((x) => <tr key={x.id}><td className="ltr">{x.code}</td><td>{x.nameEn}</td><td>{x.nameAr}</td><td><button className="btn-sm" onClick={() => setD(x)}>{t('Edit')}</button></td></tr>)}</tbody></table></div>
    {d && <Dialog title={d.id ? t('Edit plant') : t('Add plant')} onClose={() => setD(null)} footer={<><button onClick={() => setD(null)}>{t('Cancel')}</button><button className="btn-primary" onClick={save}>{t('Save')}</button></>}><div className="stack">{err && <Alert tone="err">{err}</Alert>}<TextField label={t('Code')} dir="ltr" value={d.code} onChange={(e) => setD({ ...d, code: e.target.value })} /><TextField label={t('Name (English)')} value={d.nameEn} onChange={(e) => setD({ ...d, nameEn: e.target.value })} /><TextField label={t('Name (Arabic)')} value={d.nameAr} onChange={(e) => setD({ ...d, nameAr: e.target.value })} /><TextField label={t('Address')} value={d.address} onChange={(e) => setD({ ...d, address: e.target.value })} /></div></Dialog>}</div>;
}
const UNITS = ['kg', 'tonne', 'L', 'm3', 'bag', 'drum'];
function MaterialsTab() {
  const t = useT(); const qc = useQueryClient(); const m = useQuery({ queryKey: ['materials'], queryFn: () => get<any[]>('/materials') }); const [d, setD] = useState<any>(null); const [err, setErr] = useState('');
  const save = async () => { setErr(''); const body = { ...d, conversionFactor: d.conversionFactor || null, densityKgPerM3: d.densityKgPerM3 || null, wastagePct: d.wastagePct || '0' }; try { d.id ? await put(`/materials/${d.id}`, body) : await post('/materials', body); setD(null); void qc.invalidateQueries({ queryKey: ['materials'] }); } catch (e: any) { setErr(e.message); } };
  return <div className="card"><div className="card-head"><h2>{t('Materials & units')}</h2><span className="grow" /><button className="btn-primary" onClick={() => setD({ code: '', nameEn: '', nameAr: '', category: 'other', purchaseUnit: 'tonne', dosageUnit: 'kg', conversionFactor: '', densityKgPerM3: '', wastagePct: '0' })}>{t('Add material')}</button></div>
    <div className="table-wrap"><table className="t"><thead><tr><th>{t('Code')}</th><th>{t('Material')}</th><th>{t('Purchase unit')}</th><th>{t('Dosage unit')}</th><th className="n">{t('Conversion')}</th><th className="n">{t('Density')} kg/m³</th><th className="n">{t('Wastage')} %</th><th /></tr></thead><tbody>
      {(m.data ?? []).map((x) => <tr key={x.id}><td className="ltr">{x.code}</td><td>{x.nameEn}</td><td>{x.purchaseUnit}</td><td>{x.dosageUnit}</td><td className="n">{x.conversionFactor ? Number(x.conversionFactor) : '—'}</td><td className="n">{x.densityKgPerM3 ? Number(x.densityKgPerM3) : '—'}</td><td className="n">{Number(x.wastagePct)}</td><td><button className="btn-sm" onClick={() => setD({ ...x, conversionFactor: x.conversionFactor ? String(Number(x.conversionFactor)) : '', densityKgPerM3: x.densityKgPerM3 ? String(Number(x.densityKgPerM3)) : '', wastagePct: String(Number(x.wastagePct)) })}>{t('Edit')}</button></td></tr>)}</tbody></table></div>
    {d && <Dialog title={d.id ? t('Edit material') : t('Add material')} onClose={() => setD(null)} footer={<><button onClick={() => setD(null)}>{t('Cancel')}</button><button className="btn-primary" onClick={save}>{t('Save')}</button></>}><div className="stack">{err && <Alert tone="err">{err}</Alert>}
      <div className="row"><TextField label={t('Code')} dir="ltr" value={d.code} onChange={(e) => setD({ ...d, code: e.target.value })} /><SelectField label={t('Category')} value={d.category} onChange={(e) => setD({ ...d, category: e.target.value })}>{['cement', 'aggregate', 'sand', 'water', 'admixture', 'additive', 'fibre', 'other'].map((c) => <option key={c} value={c}>{t(c)}</option>)}</SelectField></div>
      <TextField label={t('Name (English)')} value={d.nameEn} onChange={(e) => setD({ ...d, nameEn: e.target.value })} /><TextField label={t('Name (Arabic)')} value={d.nameAr} onChange={(e) => setD({ ...d, nameAr: e.target.value })} />
      <div className="row"><SelectField label={t('Purchase unit')} value={d.purchaseUnit} onChange={(e) => setD({ ...d, purchaseUnit: e.target.value })}>{UNITS.map((u) => <option key={u}>{u}</option>)}</SelectField><SelectField label={t('Dosage unit (in mixes)')} value={d.dosageUnit} onChange={(e) => setD({ ...d, dosageUnit: e.target.value })}>{UNITS.map((u) => <option key={u}>{u}</option>)}</SelectField></div>
      <NumField label={t('Conversion factor')} unit={`${d.dosageUnit}/${d.purchaseUnit}`} value={d.conversionFactor} onChange={(v) => setD({ ...d, conversionFactor: v })} hint={t('Required for bag/drum; optional override otherwise.')} /><NumField label={t('Density')} unit="kg/m³" value={d.densityKgPerM3} onChange={(v) => setD({ ...d, densityKgPerM3: v })} hint={t('Required when converting between mass and volume units.')} /><NumField label={t('Wastage')} unit="%" value={d.wastagePct} onChange={(v) => setD({ ...d, wastagePct: v })} /></div></Dialog>}</div>;
}
function TaxTab() {
  const t = useT(); const { can } = useAuth(); const qc = useQueryClient(); const p = useQuery({ queryKey: ['taxpol'], queryFn: () => get<any[]>('/tax-policies') }); const [d, setD] = useState<any>(null); const [ver, setVer] = useState<any>(null); const [ref, setRef] = useState(''); const [err, setErr] = useState('');
  const reload = () => void qc.invalidateQueries({ queryKey: ['taxpol'] });
  const save = async () => { setErr(''); try { await post('/tax-policies', d); setD(null); reload(); } catch (e: any) { setErr(e.message); } };
  const verify = async () => { setErr(''); try { await post(`/tax-policies/${ver.id}/verify`, { reference: ref }); setVer(null); setRef(''); reload(); } catch (e: any) { setErr(e.message); } };
  return <div className="card stack"><Alert tone="warn" title={t('Tax rules are not built in')}>{t('Quotations that depend on a policy cannot be issued until an authorised user verifies it against an official source. Demo policies are illustrative only.')}</Alert>
    <div className="card-head"><h2>{t('Tax policy versions')}</h2><span className="grow" />{can('tax.manage') && <button className="btn-primary" onClick={() => setD({ policyKey: 'general', name: '', ratePct: '16', taxableComponents: ['concrete', 'delivery', 'pumping', 'other'], deductionAmount: '0', deductionBasis: 'per_document', nonNegativeBase: true, exemptionNote: '', sourceReference: '', validFrom: new Date().toISOString().slice(0, 10) })}>{t('New policy version')}</button>}</div>
    {err && <Alert tone="err">{err}</Alert>}
    <div className="table-wrap"><table className="t"><thead><tr><th>{t('Policy')}</th><th>{t('Status')}</th><th className="n">{t('Rate')}</th><th>{t('Taxable components')}</th><th>{t('Deduction')}</th><th>{t('Source / verification')}</th><th /></tr></thead><tbody>
      {(p.data ?? []).map((x) => <tr key={x.id}><td><strong>{x.name}</strong><div className="muted small">{x.policyKey} · {t('from')} {x.validFrom}</div></td><td><StatusBadge status={x.status} /></td><td className="n">{Number(x.ratePct)}%</td><td className="small">{x.taxableComponents.join(', ')}</td><td className="small">{Number(x.deductionAmount) > 0 ? `${Number(x.deductionAmount)} JOD ${t(x.deductionBasis.replace('_', ' '))}` : '—'}{x.nonNegativeBase ? '' : ` (${t('base can go negative')})`}</td>
        <td className="small">{x.sourceReference || <span className="badge warn">{t('No source recorded')}</span>}{x.verifiedAt && <div className="muted">{t('Verified')} {dateTime(x.verifiedAt)}: {x.verificationReference}</div>}</td><td>{can('tax.verify') && ['draft', 'demo'].includes(x.status) && <button className="btn-sm btn-primary" onClick={() => setVer(x)}>{t('Verify')}</button>}</td></tr>)}</tbody></table></div>
    {d && <Dialog wide title={t('New tax policy version')} onClose={() => setD(null)} footer={<><button onClick={() => setD(null)}>{t('Cancel')}</button><button className="btn-primary" onClick={save} disabled={!d.name}>{t('Save draft policy')}</button></>}><div className="stack">{err && <Alert tone="err">{err}</Alert>}
      <div className="row"><TextField label={t('Policy name')} value={d.name} onChange={(e) => setD({ ...d, name: e.target.value })} /><TextField label={t('Policy key')} dir="ltr" value={d.policyKey} onChange={(e) => setD({ ...d, policyKey: e.target.value })} hint={t('Versions with the same key replace each other over time.')} /></div>
      <div className="row"><NumField label={t('Rate')} unit="%" value={d.ratePct} onChange={(v) => setD({ ...d, ratePct: v })} /><TextField label={t('Effective from')} type="date" value={d.validFrom} onChange={(e) => setD({ ...d, validFrom: e.target.value })} /></div>
      <fieldset style={{ border: 0, padding: 0 }}><legend style={{ fontWeight: 550, fontSize: 14 }}>{t('Taxable components')}</legend><div className="hstack">{['concrete', 'delivery', 'pumping', 'other'].map((c) => <label key={c} className="hstack"><input type="checkbox" checked={d.taxableComponents.includes(c)} onChange={(e) => setD({ ...d, taxableComponents: e.target.checked ? [...d.taxableComponents, c] : d.taxableComponents.filter((x: string) => x !== c) })} />{t(c)}</label>)}</div></fieldset>
      <div className="row"><NumField label={t('Deduction amount (if any)')} unit="JOD" value={d.deductionAmount} onChange={(v) => setD({ ...d, deductionAmount: v })} /><SelectField label={t('Deduction basis')} value={d.deductionBasis} onChange={(e) => setD({ ...d, deductionBasis: e.target.value })}><option value="per_m3">{t('per m³')}</option><option value="per_line">{t('per line (same mix and rate counted once)')}</option><option value="per_document">{t('per document')}</option></SelectField></div>
      <label className="hstack"><input type="checkbox" checked={d.nonNegativeBase} onChange={(e) => setD({ ...d, nonNegativeBase: e.target.checked })} />{t('Taxable base cannot go below zero')}</label>
      <AreaField label={t('Exemption details')} value={d.exemptionNote} onChange={(e) => setD({ ...d, exemptionNote: e.target.value })} /><AreaField label={t('Source / reference')} value={d.sourceReference} onChange={(e) => setD({ ...d, sourceReference: e.target.value })} hint={t('Required before verification.')} /></div></Dialog>}
    {ver && <Dialog title={t('Verify tax policy')} onClose={() => setVer(null)} footer={<><button onClick={() => setVer(null)}>{t('Cancel')}</button><button className="btn-primary" onClick={verify} disabled={ref.length < 5}>{t('Verify policy')}</button></>}><div className="stack">{err && <Alert tone="err">{err}</Alert>}<p>{t('By verifying you confirm “{n}” matches the applicable official rule. This is recorded with your name and the reference below, and its economics become immutable.', { n: ver.name })}</p><AreaField label={t('Verification source / reference')} value={ref} onChange={(e) => setRef(e.target.value)} /></div></Dialog>}</div>;
}
function TermsTab() {
  const t = useT(); const { can } = useAuth(); const qc = useQueryClient(); const x = useQuery({ queryKey: ['terms'], queryFn: () => get<any[]>('/terms') }); const [d, setD] = useState<any>(null); const [err, setErr] = useState('');
  const reload = () => void qc.invalidateQueries({ queryKey: ['terms'] });
  const save = async () => { try { await post('/terms', d); setD(null); reload(); } catch (e: any) { setErr(e.message); } };
  return <div className="card stack"><Alert tone="info">{t('Terms wording is entered and approved by your company. Nothing here is pre-approved legal text.')}</Alert>
    <div className="card-head"><h2>{t('Terms versions')}</h2><span className="grow" /><button className="btn-primary" onClick={() => setD({ name: '', clauses: [{ title: '', text: '' }] })}>{t('New terms version')}</button></div>
    {(x.data ?? []).map((v) => <div key={v.id} className="qitem" style={{ alignItems: 'flex-start' }}><div><div className="t1">{v.name} <span className="muted">v{v.version}</span></div><div className="small muted">{v.clauses.length} {t('clauses')}</div><ol className="small" style={{ paddingInlineStart: 18 }}>{v.clauses.map((c: any, i: number) => <li key={i}><strong>{c.title}</strong> {c.text}</li>)}</ol></div><div className="hstack"><StatusBadge status={v.status === 'approved' ? 'approved' : 'draft'} />{v.status === 'draft' && <button className="btn-sm btn-primary" onClick={async () => { await post(`/terms/${v.id}/approve`); reload(); }}>{t('Approve terms')}</button>}</div></div>)}
    {d && <Dialog wide title={t('New terms version')} onClose={() => setD(null)} footer={<><button onClick={() => setD(null)}>{t('Cancel')}</button><button className="btn-primary" onClick={save} disabled={!d.name || d.clauses.some((c: any) => !c.title || !c.text)}>{t('Save draft terms')}</button></>}><div className="stack">{err && <Alert tone="err">{err}</Alert>}<TextField label={t('Name')} value={d.name} onChange={(e) => setD({ ...d, name: e.target.value })} />
      {d.clauses.map((c: any, i: number) => <div key={i} className="stack-sm"><TextField label={`${t('Clause title')} ${i + 1}`} value={c.title} onChange={(e) => setD({ ...d, clauses: d.clauses.map((y: any, j: number) => (j === i ? { ...y, title: e.target.value } : y)) })} /><AreaField label={t('Clause text')} value={c.text} onChange={(e) => setD({ ...d, clauses: d.clauses.map((y: any, j: number) => (j === i ? { ...y, text: e.target.value } : y)) })} /></div>)}
      <button onClick={() => setD({ ...d, clauses: [...d.clauses, { title: '', text: '' }] })}>{t('Add clause')}</button></div></Dialog>}</div>;
}
function PoliciesTab() {
  const t = useT(); const qc = useQueryClient(); const p = useQuery({ queryKey: ['policies'], queryFn: () => get<any[]>('/pricing-policies') }); const plants = useQuery({ queryKey: ['plants'], queryFn: () => get<any[]>('/plants') }); const mixes = useQuery({ queryKey: ['mixes'], queryFn: () => get<any[]>('/mixes') }); const [d, setD] = useState<any>(null); const [err, setErr] = useState('');
  const save = async () => { try { await post('/pricing-policies', { ...d, plantId: d.plantId || null, mixId: d.mixId || null }); setD(null); void qc.invalidateQueries({ queryKey: ['policies'] }); } catch (e: any) { setErr(e.message); } };
  return <div className="card stack"><div className="card-head"><h2>{t('Commercial pricing policies')}</h2><span className="grow" /><button className="btn-primary" onClick={() => setD({ name: '', mode: 'gross_margin', pct: '18', minMarginPct: '12', plantId: '', mixId: '', validFrom: new Date().toISOString().slice(0, 10) })}>{t('New policy version')}</button></div>
    <p className="small muted">{t('A change in target margin creates a new commercial policy version — never a new technical recipe. The most specific policy (mix + plant, then mix, then plant, then default) applies.')}</p>
    <div className="table-wrap"><table className="t"><thead><tr><th>{t('Policy')}</th><th>{t('Applies to')}</th><th>{t('Mode')}</th><th className="n">{t('Target')}</th><th className="n">{t('Approval below margin')}</th><th>{t('Effective')}</th></tr></thead><tbody>
      {(p.data ?? []).map((x) => <tr key={x.id}><td>{x.name} <span className="chip">v{x.version}</span></td><td>{x.mixId ? mixes.data?.find((m) => m.id === x.mixId)?.code : t('All mixes')} / {x.plantId ? plants.data?.find((y) => y.id === x.plantId)?.code : t('all plants')}</td><td>{x.mode === 'markup' ? t('Markup') : t('Gross margin')}</td><td className="n">{Number(x.pct)}%</td><td className="n">{Number(x.minMarginPct)}%</td><td>{x.validFrom} → {x.validTo ?? '…'}</td></tr>)}</tbody></table></div>
    {d && <Dialog title={t('New pricing policy version')} onClose={() => setD(null)} footer={<><button onClick={() => setD(null)}>{t('Cancel')}</button><button className="btn-primary" onClick={save} disabled={!d.name}>{t('Publish policy')}</button></>}><div className="stack">{err && <Alert tone="err">{err}</Alert>}<TextField label={t('Name')} value={d.name} onChange={(e) => setD({ ...d, name: e.target.value })} />
      <SelectField label={t('Pricing mode')} value={d.mode} onChange={(e) => setD({ ...d, mode: e.target.value })}><option value="gross_margin">{t('Gross margin: price = cost ÷ (1 − margin)')}</option><option value="markup">{t('Markup: price = cost × (1 + markup)')}</option></SelectField>
      <div className="row"><NumField label={d.mode === 'markup' ? t('Markup') : t('Target gross margin')} unit="%" value={d.pct} onChange={(v) => setD({ ...d, pct: v })} /><NumField label={t('Approval required below margin')} unit="%" value={d.minMarginPct} onChange={(v) => setD({ ...d, minMarginPct: v })} /></div>
      <div className="row"><SelectField label={t('Plant (optional)')} value={d.plantId} onChange={(e) => setD({ ...d, plantId: e.target.value })}><option value="">{t('All plants')}</option>{(plants.data ?? []).map((x) => <option key={x.id} value={x.id}>{x.nameEn}</option>)}</SelectField><SelectField label={t('Mix (optional)')} value={d.mixId} onChange={(e) => setD({ ...d, mixId: e.target.value })}><option value="">{t('All mixes')}</option>{(mixes.data ?? []).map((x) => <option key={x.id} value={x.id}>{x.code}</option>)}</SelectField></div>
      <TextField label={t('Effective from')} type="date" value={d.validFrom} onChange={(e) => setD({ ...d, validFrom: e.target.value })} /></div></Dialog>}</div>;
}
